export const images = {
    logo: "/white-logo.svg",
    carShape: "/car-shape.png",
    client: "/client.png",
    car: "/hero-car-1.png",
    about1: "/01.jpg",
    about2: "/02.jpg",
    car1: "/car1.png",
    car2: "/car2.png",
    car3: "/car3.png",
    car4: "/car4.png",
    car5: "/car5.png",
    car6: "/car6.png",
    client2: "/client1.jpg",
    client3: "/client2.jpg",
    client4: "/client3.jpg",
}